# -*- coding: utf-8 -*-
"""weight_finder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TPDEAnXV-Zs6RO7CpePaKT5MF_Qys3aS
"""

!pip install biopython ete3 numpy scipy

import numpy as np
import random
from Bio import AlignIO
from Bio.Phylo.TreeConstruction import DistanceMatrix, DistanceTreeConstructor
from ete3 import Tree

# =========================================================
# 2) Φόρτωση alignment
# =========================================================
alignment = AlignIO.read("alignment.fasta", "fasta")
taxa = [rec.id for rec in alignment]
aln = np.array([list(rec.seq) for rec in alignment])
n_taxa, n_sites = aln.shape

# =========================================================
# 3) Φόρτωση reference tree (UNROOTED)
# =========================================================
ref_tree = Tree("reference_tree.nwk", format=1)
ref_tree.unroot()

# =========================================================
# 4) Κατηγορίες θέσεων (0-based)
# =========================================================
SNP_sites   = set([1, 5, 8, 12])
INDEL_sites = set([3, 7, 15])
MICRO_sites = set([20, 21, 22, 23])

# =========================================================
# 5) Weighted distance matrix (σωστό INDEL handling)
# =========================================================
def weighted_distance_matrix(w_snp, w_indel, w_micro, w_other=1.0):
    D = np.zeros((n_taxa, n_taxa))

    for i in range(n_taxa):
        for j in range(i + 1, n_taxa):
            d = 0.0
            for k in range(n_sites):
                a, b = aln[i, k], aln[j, k]

                if a == b:
                    continue

                # gap-gap: καμία πληροφορία
                if a == '-' and b == '-':
                    continue

                # gap vs nucleotide → INDEL
                if a == '-' or b == '-':
                    d += w_indel
                    continue

                # nucleotide vs nucleotide
                if k in MICRO_sites:
                    d += w_micro
                elif k in SNP_sites:
                    d += w_snp
                else:
                    d += w_other

            D[i, j] = D[j, i] = d

    return D

# =========================================================
# 6) Neighbor Joining tree (όντως NJ)
# =========================================================
def nj_tree_from_dist(D):
    lower_tri = []
    for i in range(len(D)):
        lower_tri.append(list(D[i, :i+1]))

    dm = DistanceMatrix(names=taxa, matrix=lower_tri)
    constructor = DistanceTreeConstructor()
    tree = constructor.nj(dm)

    t = Tree(tree.format("newick"), format=1)
    t.unroot()
    return t

# =========================================================
# 7) RF distance (unrooted)
# =========================================================
def rf_distance(tree, ref_tree):
    tree.unroot()
    rf, max_rf, *_ = tree.robinson_foulds(
        ref_tree,
        unrooted_trees=True
    )
    return rf

D = weighted_distance_matrix(1, 1, 1)
t = nj_tree_from_dist(D)
print(t)

# =========================================================
# 8) Genetic Algorithm (βελτιωμένος)
# =========================================================
POP_SIZE = 40
GENERATIONS = 50
MUTATION_RATE = 0.2
WEIGHT_BOUNDS = [(0.1, 10), (0.1, 10), (0.1, 10)]  # SNP, INDEL, MICRO

def normalize(weights):
    s = sum(weights)
    return [w / s for w in weights]

# αρχικός πληθυσμός
population = [
    normalize([random.uniform(low, high) for low, high in WEIGHT_BOUNDS])
    for _ in range(POP_SIZE)
]

best_score = float("inf")
best_weights = None
best_tree = None

for gen in range(GENERATIONS):
    fitnesses = []
    trees = []

    for ind in population:
        w_snp, w_indel, w_micro = ind
        D = weighted_distance_matrix(w_snp, w_indel, w_micro)
        tree = nj_tree_from_dist(D)
        rf = rf_distance(tree, ref_tree)

        fitnesses.append(rf)
        trees.append(tree)

    # ταξινόμηση
    idx = np.argsort(fitnesses)
    population = [population[i] for i in idx]
    fitnesses = [fitnesses[i] for i in idx]
    trees = [trees[i] for i in idx]

    # καλύτερο
    if fitnesses[0] < best_score:
        best_score = fitnesses[0]
        best_weights = population[0]
        best_tree = trees[0]

    # elitism
    next_population = population[:POP_SIZE // 2]

    # crossover + mutation
    while len(next_population) < POP_SIZE:
        p1, p2 = random.sample(next_population, 2)
        child = [random.choice([p1[i], p2[i]]) for i in range(3)]

        # mutation
        for i in range(3):
            if random.random() < MUTATION_RATE:
                low, high = WEIGHT_BOUNDS[i]
                child[i] = random.uniform(low, high)

        child = normalize(child)
        next_population.append(child)

    population = next_population

    print(
        f"Gen {gen+1:02d} | Best RF: {best_score} | "
        f"Weights (SNP, INDEL, MICRO): {best_weights}"
    )

# =========================================================
# 9) Αποθήκευση καλύτερου δέντρου
# =========================================================
best_tree.write(
    outfile="best_tree_weighted_NJ_unrooted.tre",
    format=1
)

print("\n=== FINAL RESULT ===")
print("Best normalized weights [SNP, INDEL, MICRO]:", best_weights)
print("Best RF distance:", best_score)

for w in [
    (1,1,1),
    (10,1,1),
    (1,10,1),
    (1,1,10),
    (0.9,0.05,0.05),
    (0.05,0.9,0.05),
]:
    D = weighted_distance_matrix(*w)
    t = nj_tree_from_dist(D)
    print(w, rf_distance(t, ref_tree))

best = 999
seen = set()

for _ in range(500):
    w = np.random.dirichlet([1,1,1])
    D = weighted_distance_matrix(*w)
    t = nj_tree_from_dist(D)
    rf = rf_distance(t, ref_tree)
    seen.add(rf)
    best = min(best, rf)

print("RF values seen:", sorted(seen))
print("Best RF:", best)

# =========================================================
# 1) Εγκατάσταση & imports
# =========================================================
!pip install biopython ete3 numpy scipy

import numpy as np
import random
from Bio import AlignIO
from Bio.Phylo.TreeConstruction import DistanceMatrix, DistanceTreeConstructor
from ete3 import Tree

# =========================================================
# 2) Φόρτωση alignment
# =========================================================
alignment = AlignIO.read("alignment.fasta", "fasta")
taxa = [rec.id for rec in alignment]
aln = np.array([list(rec.seq) for rec in alignment])
n_taxa, n_sites = aln.shape

# =========================================================
# 3) Φόρτωση reference tree (UNROOTED)
# =========================================================
ref_tree = Tree("reference1.tre", format=1)
ref_tree.unroot()

# =========================================================
# 4) Κατηγορίες θέσεων (0-based)
# =========================================================
SNP_sites   = set([1, 5, 8, 12])
INDEL_sites = set([3, 7, 15])
MICRO_sites = set([20, 21, 22, 23])

# =========================================================
# 5) Weighted distance matrix (σωστό INDEL handling)
# =========================================================
def weighted_distance_matrix(w_snp, w_indel, w_micro, w_other=1.0):
    D = np.zeros((n_taxa, n_taxa))

    for i in range(n_taxa):
        for j in range(i + 1, n_taxa):
            d = 0.0
            for k in range(n_sites):
                a, b = aln[i, k], aln[j, k]

                if a == b:
                    continue

                # gap-gap: καμία πληροφορία
                if a == '-' and b == '-':
                    continue

                # gap vs nucleotide → INDEL
                if a == '-' or b == '-':
                    d += w_indel
                    continue

                # nucleotide vs nucleotide
                if k in MICRO_sites:
                    d += w_micro
                elif k in SNP_sites:
                    d += w_snp
                else:
                    d += w_other

            D[i, j] = D[j, i] = d

    return D

# =========================================================
# 6) Neighbor Joining tree (όντως NJ)
# =========================================================
def nj_tree_from_dist(D):
    lower_tri = []
    for i in range(len(D)):
        lower_tri.append(list(D[i, :i+1]))

    dm = DistanceMatrix(names=taxa, matrix=lower_tri)
    constructor = DistanceTreeConstructor()
    tree = constructor.nj(dm)

    t = Tree(tree.format("newick"), format=1)
    t.unroot()
    return t

# =========================================================
# 7) RF distance (unrooted)
# =========================================================
def rf_distance(tree, ref_tree):
    tree.unroot()
    rf, max_rf, *_ = tree.robinson_foulds(
        ref_tree,
        unrooted_trees=True
    )
    return rf

D = weighted_distance_matrix(1, 1, 1)
t = nj_tree_from_dist(D)
print(t)

# =========================================================
# 8) Genetic Algorithm (βελτιωμένος)
# =========================================================
POP_SIZE = 40
GENERATIONS = 50
MUTATION_RATE = 0.2
WEIGHT_BOUNDS = [(0.1, 10), (0.1, 10), (0.1, 10)]  # SNP, INDEL, MICRO

def normalize(weights):
    s = sum(weights)
    return [w / s for w in weights]

# αρχικός πληθυσμός
population = [
    normalize([random.uniform(low, high) for low, high in WEIGHT_BOUNDS])
    for _ in range(POP_SIZE)
]

best_score = float("inf")
best_weights = None
best_tree = None

for gen in range(GENERATIONS):
    fitnesses = []
    trees = []

    for ind in population:
        w_snp, w_indel, w_micro = ind
        D = weighted_distance_matrix(w_snp, w_indel, w_micro)
        tree = nj_tree_from_dist(D)
        rf = rf_distance(tree, ref_tree)

        fitnesses.append(rf)
        trees.append(tree)

    # ταξινόμηση
    idx = np.argsort(fitnesses)
    population = [population[i] for i in idx]
    fitnesses = [fitnesses[i] for i in idx]
    trees = [trees[i] for i in idx]

    # καλύτερο
    if fitnesses[0] < best_score:
        best_score = fitnesses[0]
        best_weights = population[0]
        best_tree = trees[0]

    # elitism
    next_population = population[:POP_SIZE // 2]

    # crossover + mutation
    while len(next_population) < POP_SIZE:
        p1, p2 = random.sample(next_population, 2)
        child = [random.choice([p1[i], p2[i]]) for i in range(3)]

        # mutation
        for i in range(3):
            if random.random() < MUTATION_RATE:
                low, high = WEIGHT_BOUNDS[i]
                child[i] = random.uniform(low, high)

        child = normalize(child)
        next_population.append(child)

    population = next_population

    print(
        f"Gen {gen+1:02d} | Best RF: {best_score} | "
        f"Weights (SNP, INDEL, MICRO): {best_weights}"
    )

# =========================================================
# 9) Αποθήκευση καλύτερου δέντρου
# =========================================================
best_tree.write(
    outfile="best_tree_weighted_NJ_unrooted.tre",
    format=1
)

print("\n=== FINAL RESULT ===")
print("Best normalized weights [SNP, INDEL, MICRO]:", best_weights)
print("Best RF distance:", best_score)

# =========================================================
# 1) Εγκατάσταση & imports
# =========================================================
!pip install biopython ete3 numpy scipy

import numpy as np
import random
from Bio import AlignIO
from Bio.Phylo.TreeConstruction import DistanceMatrix, DistanceTreeConstructor
from ete3 import Tree

# =========================================================
# 2) Φόρτωση alignment
# =========================================================
alignment = AlignIO.read("alignment.fasta", "fasta")
taxa = [rec.id for rec in alignment]
aln = np.array([list(rec.seq) for rec in alignment])
n_taxa, n_sites = aln.shape

# =========================================================
# 3) Φόρτωση reference tree (UNROOTED)
# =========================================================
ref_tree = Tree("reference1.tre", format=1)
ref_tree.unroot()

# =========================================================
# 4) Κατηγορίες θέσεων (0-based)
# =========================================================
SNP_sites   = set([1, 5, 8, 12])
INDEL_sites = set([3, 7, 15])
MICRO_sites = set([20, 21, 22, 23])

# =========================================================
# 5) Weighted distance matrix (σωστό INDEL handling)
# =========================================================
def weighted_distance_matrix(w_snp, w_indel, w_micro, w_other=1.0):
    D = np.zeros((n_taxa, n_taxa))

    for i in range(n_taxa):
        for j in range(i + 1, n_taxa):
            d = 0.0
            for k in range(n_sites):
                a, b = aln[i, k], aln[j, k]

                if a == b:
                    continue

                # gap-gap: καμία πληροφορία
                if a == '-' and b == '-':
                    continue

                # gap vs nucleotide → INDEL
                if a == '-' or b == '-':
                    d += w_indel
                    continue

                # nucleotide vs nucleotide
                if k in MICRO_sites:
                    d += w_micro
                elif k in SNP_sites:
                    d += w_snp
                else:
                    d += w_other

            D[i, j] = D[j, i] = d

    return D

# =========================================================
# 6) Neighbor Joining tree (όντως NJ)
# =========================================================
def nj_tree_from_dist(D):
    lower_tri = []
    for i in range(len(D)):
        lower_tri.append(list(D[i, :i+1]))

    dm = DistanceMatrix(names=taxa, matrix=lower_tri)
    constructor = DistanceTreeConstructor()
    tree = constructor.nj(dm)

    t = Tree(tree.format("newick"), format=1)
    t.unroot()
    return t

# =========================================================
# 7) RF distance (unrooted)
# =========================================================
def rf_distance(tree, ref_tree):
    tree.unroot()
    rf, max_rf, *_ = tree.robinson_foulds(
        ref_tree,
        unrooted_trees=True
    )
    return rf

D = weighted_distance_matrix(1, 1, 1)
t = nj_tree_from_dist(D)
print(t)

# =========================================================
# RANDOM SEARCH
# =========================================================

N_RANDOM = 3000
TOP_K = 40

candidates = []

for i in range(N_RANDOM):

    weights = normalize([random.uniform(0.1,10) for _ in range(3)])

    w_snp, w_indel, w_micro = weights

    D = weighted_distance_matrix(w_snp, w_indel, w_micro)
    tree = nj_tree_from_dist(D)

    rf = compute_rf(tree, ref_tree)

    candidates.append((rf, weights, tree))

    if (i+1) % 500 == 0:
        print(f"Random sample {i+1}")

# ταξινόμηση
candidates.sort(key=lambda x: x[0])

# κρατάμε τα καλύτερα
population = [c[1] for c in candidates[:TOP_K]]

best_score = candidates[0][0]
best_weights = candidates[0][1]
best_tree = candidates[0][2]

print("\nBest from random search:", best_score)

# =========================================================
# GENETIC ALGORITHM REFINEMENT
# =========================================================

GENERATIONS = 30
MUTATION_RATE = 0.2
POP_SIZE = TOP_K

for gen in range(GENERATIONS):

    fitnesses = []
    trees = []

    for ind in population:

        w_snp, w_indel, w_micro = ind

        D = weighted_distance_matrix(w_snp, w_indel, w_micro)
        tree = nj_tree_from_dist(D)

        rf = compute_rf(tree, ref_tree)

        fitnesses.append(rf)
        trees.append(tree)

    # sort population
    idx = np.argsort(fitnesses)

    population = [population[i] for i in idx]
    fitnesses = [fitnesses[i] for i in idx]
    trees = [trees[i] for i in idx]

    # update best
    if fitnesses[0] < best_score:
        best_score = fitnesses[0]
        best_weights = population[0]
        best_tree = trees[0]

   # 4️⃣ early stopping
    if no_improve >= MAX_STAGNATION:
        print(f"Early stopping: no improvement for {MAX_STAGNATION} generations")
        break

    # elitism
    next_population = population[:POP_SIZE//2]

    # crossover + mutation
    while len(next_population) < POP_SIZE:

        p1, p2 = random.sample(next_population, 2)

        child = [(p1[i] + p2[i]) / 2 for i in range(3)]

        # mutation
        for i in range(3):

            if random.random() < MUTATION_RATE:

                child[i] += random.gauss(0,0.1)

                child[i] = max(0.01, child[i])

        child = normalize(child)

        next_population.append(child)

    population = next_population

    print(
        f"Gen {gen+1:02d} | Best RF: {best_score} | "
        f"Weights: {best_weights}"
    )

# =========================================================
# 9) Αποθήκευση καλύτερου δέντρου
# =========================================================
best_tree.write(
    outfile="best_tree_weighted_NJ_unrooted.tre",
    format=1
)

print("\n=== FINAL RESULT ===")
print("Best normalized weights [SNP, INDEL, MICRO]:", best_weights)
print("Best RF distance:", best_score)
